/* tslint:disable */
/* eslint-disable */
/**
 * Virtex API
 * Virtex API
 *
 * The version of the OpenAPI document: v1
 * Contact: info@virtex.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

